name: streamlit
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13.5
  - pip
  - streamlit
  - pandas
  - numpy
  - plotly
  - matplotlib
  - xlsxwriter
  - requests
  - pip:
    - prophet