name: Python Package using Conda

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Conda environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        environment-file: environment.yml
        activate-environment: epex-analysis
        cache-environment: true
        use-mamba: true # Mamba is a faster drop-in replacement for conda

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      shell: bash -l {0}

    - name: Test with pytest
      run: |
        PYTHONPATH=. pytest tests/
      shell: bash -l {0}
